name: karyasiddhi_frontend
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.3+1
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  go_router: ^10.0.0
  flutter_riverpod: ^2.3.0
  shared_preferences: ^2.1.0
  google_sign_in: ^6.0.2
  google_sign_in_web: ^0.11.0
  qr_flutter: ^4.0.0
  google_fonts: ^4.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

