name: task_tool_frontend
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.3+1
  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  go_router: ^14.2.7
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  google_sign_in: 6.1.6
  google_sign_in_web: 0.12.4
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

