name: task_tool_frontend
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  go_router: ^16.1.0
  flutter_riverpod: ^2.6.1
  google_sign_in: ^7.1.1
  google_sign_in_web: ^1.0.0
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/

