version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tasktool
      POSTGRES_USER: dbmasteruser
      POSTGRES_PASSWORD: example
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:

